import type { StockMove } from '../shared/models/stockMove';
import { STOCK_MOVE } from '../shared/constants/stockMoveTypes';

export const stockDB: StockMove[] = [
  {
    id: '1',
    type: STOCK_MOVE.IN,
    quantity: 100,
    date: '2026-01-01',
    product: 'iPad Pro 11 2021',
    warehouse: 'Bodega Central',
    reference: 'Ingreso inicial',
  },
  {
    id: '2',
    type: STOCK_MOVE.OUT,
    quantity: 20,
    date: '2026-01-02',
    product: 'Celular Gaming Xiaomi',
    warehouse: 'Bodega Norte',
    reference: 'Venta',
  },
  {
    id: '3',
    type: STOCK_MOVE.ADJUST,
    quantity: 15,
    date: '2026-01-03',
    product: 'Laptop Dell XPS 13',
    warehouse: 'Bodega Central',
    reference: 'Ajuste inventario',
  },
  {
    id: '4',
    type: STOCK_MOVE.IN,
    quantity: 50,
    date: '2026-01-04',
    product: 'Monitor LG UltraWide',
    warehouse: 'Bodega Norte',
    reference: 'Ingreso proveedor',
  },
  {
    id: '5',
    type: STOCK_MOVE.OUT,
    quantity: 5,
    date: '2026-01-05',
    product: 'Teclado Mecánico Keychron',
    warehouse: 'Bodega Central',
    reference: 'Venta minorista',
  },
  {
    id: '6',
    type: STOCK_MOVE.ADJUST,
    quantity: 8,
    date: '2026-01-06',
    product: 'Mouse Logitech MX Master 3',
    warehouse: 'Bodega Norte',
    reference: 'Ajuste por daño',
  },
  {
    id: '7',
    type: STOCK_MOVE.IN,
    quantity: 30,
    date: '2026-01-07',
    product: 'Tablet Samsung Galaxy Tab S7',
    warehouse: 'Bodega Central',
    reference: 'Ingreso proveedor',
  },
  {
    id: '8',
    type: STOCK_MOVE.OUT,
    quantity: 12,
    date: '2026-01-08',
    product: 'Auriculares Sony WH-1000XM4',
    warehouse: 'Bodega Norte',
    reference: 'Venta online',
  },
  {
    id: '9',
    type: STOCK_MOVE.ADJUST,
    quantity: 3,
    date: '2026-01-09',
    product: 'Smartwatch Apple Watch SE',
    warehouse: 'Bodega Central',
    reference: 'Ajuste por extravío',
  },
  {
    id: '10',
    type: STOCK_MOVE.IN,
    quantity: 60,
    date: '2026-01-10',
    product: 'Impresora HP LaserJet',
    warehouse: 'Bodega Norte',
    reference: 'Ingreso proveedor',
  },
  {
    id: '11',
    type: STOCK_MOVE.OUT,
    quantity: 7,
    date: '2026-01-11',
    product: 'Router TP-Link Archer',
    warehouse: 'Bodega Central',
    reference: 'Venta minorista',
  },
  {
    id: '12',
    type: STOCK_MOVE.ADJUST,
    quantity: 2,
    date: '2026-01-12',
    product: 'Disco SSD Samsung 1TB',
    warehouse: 'Bodega Norte',
    reference: 'Ajuste por error',
  },
  {
    id: '13',
    type: STOCK_MOVE.IN,
    quantity: 25,
    date: '2026-01-13',
    product: 'Cámara Canon EOS M50',
    warehouse: 'Bodega Central',
    reference: 'Ingreso proveedor',
  },
  {
    id: '14',
    type: STOCK_MOVE.OUT,
    quantity: 9,
    date: '2026-01-14',
    product: 'Proyector Epson',
    warehouse: 'Bodega Norte',
    reference: 'Venta corporativa',
  },
  {
    id: '15',
    type: STOCK_MOVE.ADJUST,
    quantity: 4,
    date: '2026-01-15',
    product: 'Silla Ergonómica',
    warehouse: 'Bodega Central',
    reference: 'Ajuste por rotura',
  },
  {
    id: '16',
    type: STOCK_MOVE.IN,
    quantity: 40,
    date: '2026-01-16',
    product: 'Monitor Samsung Curvo',
    warehouse: 'Bodega Norte',
    reference: 'Ingreso proveedor',
  },
  {
    id: '17',
    type: STOCK_MOVE.OUT,
    quantity: 6,
    date: '2026-01-17',
    product: 'Celular iPhone 13',
    warehouse: 'Bodega Central',
    reference: 'Venta online',
  },
  {
    id: '18',
    type: STOCK_MOVE.ADJUST,
    quantity: 1,
    date: '2026-01-18',
    product: 'Tablet Lenovo Tab P11',
    warehouse: 'Bodega Norte',
    reference: 'Ajuste por devolución',
  },
  {
    id: '19',
    type: STOCK_MOVE.IN,
    quantity: 80,
    date: '2026-01-19',
    product: 'Laptop MacBook Air M2',
    warehouse: 'Bodega Central',
    reference: 'Ingreso proveedor',
  },
  {
    id: '20',
    type: STOCK_MOVE.OUT,
    quantity: 11,
    date: '2026-01-20',
    product: 'Impresora Epson EcoTank',
    warehouse: 'Bodega Norte',
    reference: 'Venta minorista',
  },
];
